import type { Metadata } from "next";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import DashboardNavbar from "../components/DashboardNavbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
        <DashboardNavbar />
        <SidebarProvider>
      <AppSidebar />
        <SidebarTrigger />
        {children}
    </SidebarProvider>
    </>
  );
}
